disallowed-methods = [
    { path = "std::iter::Iterator::zip", reason = "Please use `zip_eq_fast` if it's available. Otherwise use `zip_eq_debug`" },
    { path = "itertools::Itertools::zip_eq", reason = "Please use `zip_eq_fast` if it's available. Otherwise use `zip_eq_debug`" },
    { path = "futures::stream::select_all", reason = "Please use `risingwave_common::util::select_all` instead." },
    { path = "risingwave_common::array::JsonbVal::from_serde", reason = "Please add dedicated methods as part of `JsonbRef`/`JsonbVal`, rather than take inner `serde_json::Value` out, process, and put back." },
]
disallowed-types = [
    { path = "num_traits::AsPrimitive", reason = "unless you know" },
]
doc-valid-idents = [
    "RisingWave",
    "MinIO",
    "ProtoBuf",
    "BloomFilter",
    "gRPC",
    "PostgreSQL",
    "MySQL",
    "TopN",
    "VNode"
]
avoid-breaking-exported-api = false
upper-case-acronyms-aggressive = true
