[package]
name = "risingwave_hummock_sdk"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack", "num-traits"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
bytes = "1"
hex = "0.4"
itertools = "0.10"
parking_lot = "0.12"
parse-display = "0.6"
risingwave_common = { path = "../../common" }
risingwave_pb = { path = "../../prost" }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }
