[package]
name = "risedev"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "4", features = ["derive"] }
console = "0.15"
dialoguer = "0.10"
enum-iterator = "1"
fs-err = "2.9.0"
google-cloud-pubsub = "0.7.0"
indicatif = "0.17"
isahc = { version = "1", default-features = false, features = ["text-decoding"] }
itertools = "0.10"
kafka = { version = "0.9", default-features = false }
pulldown-cmark = "0.9"
redis = "0.22"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "2"
serde_yaml = "0.9"
tempfile = "3"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs"
] }
workspace-hack = { path = "../workspace-hack" }
yaml-rust = "0.4"
